name: Build and Push Images to ECR

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Backend
      - name: Build Backend Image
        run: |
          docker build -t acc-uw-backend ./backend

      - name: Tag Backend Image
        run: |
          docker tag acc-uw-backend:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/acc-uw-backend:latest

      - name: Push Backend Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/acc-uw-backend:latest

      # Frontend
      - name: Build Frontend Image
        run: |
          docker build -t sbi-uw-frontend ./frontend

      - name: Tag Frontend Image
        run: |
          docker tag sbi-uw-frontend:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/sbi-uw-frontend:latest

      - name: Push Frontend Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/sbi-uw-frontend:latest

